### ISSUE TITLE
Import errors 

### ISSUE THREAD

**Issue by msaharia** [mdbartos/pysheds#22] opened 2018-08-29 21:31 UTC
On a fresh installation of `pysheds`, I get import errors for geojson, affine, and pyproj.

Might trip new users. The installation of dependencies could be automated using `setuptools`

**Comment by mdbartos** [comment] 2018-08-30 21:48
Yes, that's a good idea.

Did you install using setup.py?

**Comment by msaharia** [comment] 2018-08-30 21:58
No. I installed using pip.

________________________________

**Comment by gopalam** [comment] 2021-04-09 13:10
Hi, I have a similar issue with errors from pysheds install (on  windows +anaconda + python3). The error is with lack of geojson. Trying to install geojson throws up another error- "environment is inconsistent" ... "caused by pysheds==0.2.7".  I was wondering what the workaround to this would be for this.  Thanks so much. GM

**Comment by mdbartos** [comment] 2022-01-03 23:12
This should be resolved in the current version. Please reopen an issue if the problem persists.

**Closed by mdbartos** 2022-01-03 23:12 UTC
